services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes: [.:/usr/src/app]
    ports: [5000:4000]
    # user: 1000:1000
    user: "241181586:241172993"
    environment: [JEKYLL_ENV=docker]